// Generated by CoffeeScript 1.4.0
(function() {

  describe('Meteor client-side code', function() {
    var dummyroom;
    dummyroom = {
      _id: 789
    };
    beforeEach(function() {
      return Session.set('roomClicked', 0);
    });
    describe('Template.classroom', function() {
      return describe('#activeRoom()', function() {
        it('should return true if the clicked room ID is the same as "this" room ID', function() {
          Session.set('roomClicked', 789);
          return chai.assert.equal(Template.classroom.activeRoom.apply(dummyroom), true);
        });
        return it('should return false if the clicked room ID is different than "this" room ID', function() {
          Session.set('roomClicked', 7890);
          return chai.assert.equal(Template.classroom.activeRoom.apply(dummyroom), false);
        });
      });
    });
    return describe('opentok', function() {
      xit('should create a unique session ID for each classroom', function() {});
      return xit('should add new students to an existing session', function() {});
    });
  });

}).call(this);
