// Generated by CoffeeScript 1.4.0
(function() {

  describe('Meteor client-side code', function() {
    return describe('Template.classroom', function() {
      return describe('#activeRoom()', function() {
        it('should return the id of the room name clicked', function() {
          var dummyroom;
          dummyroom = {
            _id: 789
          };
          chai.assert.equal(Template.classroom.activeRoom.apply(dummyroom), false);
          return Session.set('roomClicked', 7890);
        });
        return it('should', function() {
          return chai.assert.equal(Template.classroom.activeRoom.apply(dummyroom), true);
        });
      });
    });
  });

}).call(this);
