// Generated by CoffeeScript 1.4.0
(function() {
  var Meteor, Template;

  Meteor = {
    'is_client': true,
    'is_server': false
  };

  Template = {
    'hello': {}
  };

  describe('Meteor client-side code', function() {
    return describe('Template.chatlogs', function() {
      describe('#chatMessages()', function() {
        return it('should return an array (of chat messages)', function() {
          return chai.assert.equal(Array.isArray(Template.chatlogs.chatMessages()), true);
        });
      });
      return describe('#events', function() {
        it('should contain a click handler for the input button', function() {
          return chai.assert.property(Template.hello.events, 'click input');
        });
        return it('the input button event handler should log a message to the console', function() {
          Template.hello.events['click input']();
          return chai.assert(console.log.calledWith('You pressed the button'));
        });
      });
    });
  });

}).call(this);
